models/Citas.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "citas".
 *
 * @property int $IDcitas
 * @property string $fecha
 * @property string $hora
 * @property int|null $IDcitas_cliente
 * @property int|null $IDcitas_servicio
 *
 * @property Clientes $iDcitasCliente
 * @property Servicios $iDcitasServicio
 */
class Citas extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'citas';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['fecha', 'hora'], 'required'],
            [['fecha', 'hora'], 'safe'],
            [['fecha','hora','IDcitas_cliente','IDcitas_servicio'], 'string', 'max' => 255],
            [['IDcitas_cliente', 'IDcitas_servicio'], 'integer'],
            [['IDcitas_cliente'], 'exist', 'skipOnError' => true, 'targetClass' => Clientes::className(), 'targetAttribute' => ['IDcitas_cliente' => 'IDcliente']],
            [['IDcitas_servicio'], 'exist', 'skipOnError' => true, 'targetClass' => Servicios::className(), 'targetAttribute' => ['IDcitas_servicio' => 'IDservicio']],
            
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'IDcitas' => 'ID citas',
            'fecha' => 'Fecha',
            'hora' => 'Hora',
            'IDcitas_cliente' => 'Nombre',
            'IDcitas_servicio' => 'Servicio',
        ];
    }

    /**
     * Gets query for [[IDcitasCliente]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIDcitasCliente()
    {
        return $this->hasOne(Clientes::className(), ['IDcliente' => 'IDcitas_cliente']);
    }

    /**
     * Gets query for [[IDcitasServicio]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIDcitasServicio()
    {
        return $this->hasOne(Servicios::className(), ['IDservicio' => 'IDcitas_servicio']);
    }
    
    
}

controllers/CitasController.php
<?php

namespace app\controllers;

use app\models\Citas;
use app\models\Clientes;
use app\models\Servicios;
use app\models\CitasSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\data\ActiveDataProvider;
use yii\db\Query; 
/**
 * CitasController implements the CRUD actions for Citas model.
 */
class CitasController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Citas models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new CitasSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    //Mostrar las citas según las fechas
    
    public function actionTotal()
    {
        $searchModel = new CitasSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('total', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionEnero()
    {
        $fecha = date('Y-m-d');
        $dataProvider = new ActiveDataProvider([
                'query' => Citas::find()->where("fecha >= CAST('2022-01-01' AS date ) AND fecha <= CAST('2022-01-31' AS date )")->orderBy('hora'),
                'pagination' =>['pageSize'=>8],
            ]);
        
        $totalCitas = Citas::find()->where("fecha >= CAST('2022-01-01' AS date ) AND fecha <= CAST('2022-01-31' AS date )")->count();
        
       // $totalBeneficio = Citas::find()->where($fechaCondicion)->joinWith($servicios)->select
        
        $connection = \Yii::$app->db; 
        $query = new Query; 
        
        $insql = $connection->createCommand("SELECT SUM(s.coste) AS total FROM citas c
        LEFT JOIN servicios s ON c.IDcitas_servicio = s.IDservicio
       WHERE c.fecha >= CAST('2022-01-01' AS date ) AND c.fecha <= CAST('2022-01-31' AS date ) ");  
        $totalBeneficio=$insql->queryColumn();
        
        $insql2 = $connection->createCommand("SELECT COUNT(*) AS total FROM citas c     
        LEFT JOIN servicios s ON c.IDcitas_servicio = s.IDservicio
        WHERE c.fecha >= CAST('2022-01-01' AS date ) AND c.fecha <= CAST('2022-01-31' AS date ) AND s.nombre like 'corte pelo'");  
         $totalServiciosPelo=$insql2->queryOne();
       
       $insql3 = $connection->createCommand("SELECT COUNT(*) AS total FROM citas c     
        LEFT JOIN servicios s ON c.IDcitas_servicio = s.IDservicio
        WHERE c.fecha >= CAST('2022-01-01' AS date ) AND c.fecha <= CAST('2022-01-31' AS date ) AND s.nombre like 'Barba'");  
         $totalServiciosBarba=$insql3->queryOne();
         
        $insql4 = $connection->createCommand("SELECT COUNT(*) AS total FROM citas c     
        LEFT JOIN servicios s ON c.IDcitas_servicio = s.IDservicio
        WHERE c.fecha >= CAST('2022-01-01' AS date ) AND c.fecha <= CAST('2022-01-31' AS date ) AND s.nombre like 'tinte de barba'");  
         $totalServiciosTinteBarba=$insql4->queryOne(); 
         
        $insql5 = $connection->createCommand("SELECT COUNT(*) AS total FROM citas c     
        LEFT JOIN servicios s ON c.IDcitas_servicio = s.IDservicio
        WHERE c.fecha >= CAST('2022-01-01' AS date ) AND c.fecha <= CAST('2022-01-31' AS date ) AND s.nombre like 'Tinte de pelo'");  
         $totalServiciosTintePelo=$insql5->queryOne();
         
         $insql6 = $connection->createCommand("SELECT COUNT(*) AS total FROM citas c     
        LEFT JOIN servicios s ON c.IDcitas_servicio = s.IDservicio
        WHERE c.fecha >= CAST('2022-01-01' AS date ) AND c.fecha <= CAST('2022-01-31' AS date ) AND s.nombre like 'Corte pelo niño'");  
         $totalServiciosPeloNiño=$insql6->queryOne();
         
       $insql7 = $connection->createCommand("SELECT COUNT(*) AS total FROM citas c     
        LEFT JOIN servicios s ON c.IDcitas_servicio = s.IDservicio
        WHERE c.fecha >= CAST('2022-01-01' AS date ) AND c.fecha <= CAST('2022-01-31' AS date ) AND s.nombre like 'Cejas'");  
         $totalServiciosCejas=$insql7->queryOne();
        
        return $this->render('enero', [
                    'dp' => $dataProvider,
                    'totalCitas' => $totalCitas,
                    'totalBeneficio' => $totalBeneficio,           
                    'totalServiciosPelo' => $totalServiciosPelo, 
                    'totalServiciosBarba' => $totalServiciosBarba,
                    'totalServiciosTinteBarba' => $totalServiciosTinteBarba,
                    'totalServiciosTintePelo' => $totalServiciosTintePelo,
                    'totalServiciosPeloNiño' => $totalServiciosPeloNiño,
                    'totalServiciosCejas' => $totalServiciosCejas,
            
        ]);
    }
    
    
    
    public function actionFebrero()
    {
        $fecha = date('Y-m-d');
        $dataProvider = new ActiveDataProvider([
                'query' => Citas::find()->where("fecha >= CAST('2022-02-01' AS date ) AND fecha <= CAST('2022-02-27' AS date )")->orderBy('hora'),
                'pagination' =>['pageSize'=>8],
            ]);
        
               $totalCitas = Citas::find()->where("fecha >= CAST('2022-02-01' AS date ) AND fecha <= CAST('2022-02-27' AS date )")->count();
        
       // $totalBeneficio = Citas::find()->where($fechaCondicion)->joinWith($servicios)->select
        
        $connection = \Yii::$app->db; 
        $query = new Query; 
        
        $insql = $connection->createCommand("SELECT SUM(s.coste) AS total FROM citas c
        LEFT JOIN servicios s ON c.IDcitas_servicio = s.IDservicio
       WHERE c.fecha >= CAST('2022-02-01' AS date ) AND c.fecha <= CAST('2022-02-27' AS date ) ");  
        $totalBeneficio=$insql->queryColumn();
	   
	   $insql2 = $connection->createCommand("SELECT COUNT(*) AS total FROM citas c     
        LEFT JOIN servicios s ON c.IDcitas_servicio = s.IDservicio
        WHERE c.fecha >= CAST('2022-02-01' AS date ) AND c.fecha <= CAST('2022-02-27' AS date ) AND s.nombre like 'corte pelo'");  
         $totalServiciosPelo=$insql2->queryOne();
       
       $insql3 = $connection->createCommand("SELECT COUNT(*) AS total FROM citas c     
        LEFT JOIN servicios s ON c.IDcitas_servicio = s.IDservicio
        WHERE c.fecha >= CAST('2022-02-01' AS date ) AND c.fecha <= CAST('2022-02-27' AS date ) AND s.nombre like 'Barba'");  
         $totalServiciosBarba=$insql3->queryOne();
         
        $insql4 = $connection->createCommand("SELECT COUNT(*) AS total FROM citas c     
        LEFT JOIN servicios s ON c.IDcitas_servicio = s.IDservicio
        WHERE c.fecha >= CAST('2022-02-01' AS date ) AND c.fecha <= CAST('2022-02-27' AS date ) AND s.nombre like 'tinte de barba'");  
         $totalServiciosTinteBarba=$insql4->queryOne(); 
         
        $insql5 = $connection->createCommand("SELECT COUNT(*) AS total FROM citas c     
        LEFT JOIN servicios s ON c.IDcitas_servicio = s.IDservicio
        WHERE c.fecha >= CAST('2022-02-01' AS date ) AND c.fecha <= CAST('2022-02-27' AS date ) AND s.nombre like 'Tinte de pelo'");  
         $totalServiciosTintePelo=$insql5->queryOne();
         
         $insql6 = $connection->createCommand("SELECT COUNT(*) AS total FROM citas c     
        LEFT JOIN servicios s ON c.IDcitas_servicio = s.IDservicio
        WHERE c.fecha >= CAST('2022-02-01' AS date ) AND c.fecha <= CAST('2022-02-27' AS date ) AND s.nombre like 'Corte pelo niño'");  
         $totalServiciosPeloNiño=$insql6->queryOne();
         
       $insql7 = $connection->createCommand("SELECT COUNT(*) AS total FROM citas c     
        LEFT JOIN servicios s ON c.IDcitas_servicio = s.IDservicio
        WHERE c.fecha >= CAST('2022-02-01' AS date ) AND c.fecha <= CAST('2022-02-27' AS date ) AND s.nombre like 'Cejas'");  
         $totalServiciosCejas=$insql7->queryOne();
        
        return $this->render('febrero', [
                    'dp' => $dataProvider,
                    'totalCitas' => $totalCitas,
                    'totalBeneficio' => $totalBeneficio,           
                    'totalServiciosPelo' => $totalServiciosPelo, 
                    'totalServiciosBarba' => $totalServiciosBarba,
                    'totalServiciosTinteBarba' => $totalServiciosTinteBarba,
                    'totalServiciosTintePelo' => $totalServiciosTintePelo,
                    'totalServiciosPeloNiño' => $totalServiciosPeloNiño,
                    'totalServiciosCejas' => $totalServiciosCejas,
            
        ]);
    }
    
    
    public function actionMarzo()
    {
        $fecha = date('Y-m-d');
        $dataProvider = new ActiveDataProvider([
                'query' => Citas::find()->where("fecha >= CAST('2022-03-01' AS date ) AND fecha <= CAST('2022-03-31' AS date )")->orderBy('hora'),
                'pagination' =>['pageSize'=>8],
            ]);
        
              $totalCitas = Citas::find()->where("fecha >= CAST('2022-03-01' AS date ) AND fecha <= CAST('2022-03-31' AS date )")->count();
        
       // $totalBeneficio = Citas::find()->where($fechaCondicion)->joinWith($servicios)->select
        
        $connection = \Yii::$app->db; 
        $query = new Query; 
        
        $insql = $connection->createCommand("SELECT SUM(s.coste) AS total FROM citas c
        LEFT JOIN servicios s ON c.IDcitas_servicio = s.IDservicio

controllers/ClientesController.php
<?php

namespace app\controllers;

use app\models\Clientes;
use app\models\ClientesSearch;
use app\models\Telefonos;
//use app\models\TelefonosSearch;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

/**
 * ClientesController implements the CRUD actions for Clientes model.
 */
class ClientesController extends Controller {

    /**
     * @inheritDoc
     */
    public function behaviors() {
        return array_merge(
                parent::behaviors(),
                [
                    'verbs' => [
                        'class' => VerbFilter::className(),
                        'actions' => [
                            'delete' => ['POST'],
                        ],
                    ],
                ]
        );
    }

    /**
     * Lists all Clientes models.
     *
     * @return string
     */
    public function actionIndex() {

        $dataProvider = new ActiveDataProvider([
            'query' => Clientes::find(),
            'pagination' => ['pageSize' => 8],
        ]);

        return $this->render('index', [
                    'dp' => $dataProvider,
        ]);
    }

    public function actionModificar() {
        $searchModel = new ClientesSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

//        $searchModelTlf = new TelefonosSearch();
//        $dataProvider2 = $searchModelTlf->search($this->request->queryParams);
        
//         $telefono = Telefonos::find()->all();
//          $listaTelefono = ArrayHelper::map($telefono, 'IDtelefono', 'telefono1','telefono2');

        return $this->render('modificar', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
//                    'listaTelefono' => $listaTelefono,
//                    'searchModelTlf' => $searchModelTlf,
//                    'dataProvider2' => $dataProvider2,
        ]);
    }

    /**
     * Displays a single Clientes model.
     * @param int $IDcliente I Dcliente
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($IDcliente) {
        return $this->render('view', [
                    'model' => $this->findModel($IDcliente),
        ]);
    }

    /**
     * Creates a new Clientes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate() {
        $model = new Clientes();

        if ($this->request->isPost) {

            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['telefonos/create', 'IDcliente' => $model->IDcliente]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing Clientes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $IDcliente I Dcliente
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($IDcliente) {
        $model = $this->findModel($IDcliente);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['telefonos/create', 'IDcliente' => $model->IDcliente]);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Clientes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $IDcliente I Dcliente
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($IDcliente) {
        $this->findModel($IDcliente)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Clientes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $IDcliente I Dcliente
     * @return Clientes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($IDcliente) {
        if (($model = Clientes::findOne(['IDcliente' => $IDcliente])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

views/citas/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\bootstrap4\Modal;
use kartik\date\DatePicker;


/* @var $this yii\web\View */
/* @var $searchModel app\models\CitasSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

//$this->title = 'Citas';
//$this->params['breadcrumbs'][] = $this->title;
?>
<header>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js" crossorigin="anonymous"></script>
</header>
<body>
<?php
class CabeceraPagina {
  private $titulo;
  private $ubicacion;
  private $colorFuente;
  private $colorFondo;
  public function __construct($titulo,$ubica,$colorFuen,$colorFond)
  {
    $this->titulo=$titulo;
    $this->ubicacion=$ubica;
    $this->colorFuente=$colorFuen;
    $this->colorFondo=$colorFond;
  }
  public function mostrarHeader()
  {
    echo '<div style="font-size:30px;text-align:'.$this->ubicacion.';color:';
    echo $this->colorFuente.';background-color:'.$this->colorFondo.'">';
    echo $this->titulo;
    echo '</div>';

  }
}

$cabecera=new CabeceraPagina('MODIFICAR CITA','center','#ffffff','#11264D');
$cabecera->mostrarHeader();

?>



<div class ="row justify-content-center  p-2  ">          
    <div class = "card col-2 m-2  zoom colorManager"> 
        <div class = "card-body">
        
             <div class = "card-body card sinborde negro">
          <?php echo Html::img('@web/image/home.png');?>
             </div>
            <hr class="colorBarber">
              <?= Html::a('HOME',['site/index'],['class' => 'card-body card colorManager2'])?>
        </div>
     </div>
    
    <div class = "card col-2 m-2  zoom colorManager "> 
        <div class = "card-body">
        
             <div class = "card-body card sinborde negro">
          <?php echo Html::img('@web/image/us.png');?>
             </div>
            <hr class="colorBarber">
              <?= Html::a('CLIENTES',['clientes/index'],['class' => 'card-body card colorManager2'])?>
        </div>
     </div>
    
    <div class = "card col-2 m-2  zoom colorManager"> 
        <div class = "card-body">
        
             <div class = "card-body card sinborde negro">
          <?php echo Html::img('@web/image/ser.png');?>
             </div>
            <hr class="colorBarber">
              <?= Html::a('SERVICIOS',['servicios/index'],['class' => 'card-body card colorManager2'])?>
        </div>
     </div>
    
    <div class = "card col-2 m-2  zoom colorManager"> 
        <div class = "card-body">
        
             <div class = "card-body card sinborde negro">
          <?php echo Html::img('@web/image/pro.png');?>
             </div>     
            <hr class="colorBarber">
              <?= Html::a('PROVEEDORES',['proveedores/index'],['class' => 'card-body card colorManager2'])?>
        </div>
     </div>
    
    <div class = "card col-2 m-2  zoom colorManager"> 
        <div class = "card-body">
        
             <div class = "card-body card sinborde negro">
          <?php echo Html::img('@web/image/sto.png');?>
             </div>
            <hr class="colorBarber">
            
              <?= Html::a('PRODUCTOS',['productos/index'],['class' => 'card-body card colorManager2'])?>
        </div>
    </div>
    
</div>
<br>

    <div class ="row justify-content-center ">              
            <div class = "card col-4 m-2 colorManager"> 
        <div class = "card-body">
    
               <h5 class="card-text">
                FECHA:<br> <?php $fechaActual = date('d-m-Y'); echo $fechaActual; ?> 
            </h5>
        </div>
    </div>
                 <?= Html::a('Volver',['site/index'],['class' => 'centrar card-body card col-2 m-2 colorManager zoom'])?>                  
                 <?= Html::button('Crear citas', ['value'=>Url::to(['citas/create']),'class'=>'centrar card-body card col-2 m-2 colorManager zoom','id'=>'modalButton']) ?>
            <?php
                    Modal::begin([
                        'id'=>'modal',
                        'size'=>'50',
                    ]);
                    echo "<div id='modalContent'></div>";
                    Modal::end();
            ?>    
    </div>
    <br>
    <br>
    
    <div class="container ">
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    
    <div class="bg-white">
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            
            [
                'attribute'=>'fecha',
                'value'=>'fecha',
                'format'=>'raw',
                'filter'=>DatePicker::widget ([
                'model'=> $searchModel,
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'pickerIcon' => '<i class="fas fa-calendar-alt text-primary"></i>',
                'removeIcon' => '<i class="fas fa-trash text-danger"></i>',
                'attribute'=>'fecha',
                'pluginOptions' => [
                'autoclose' => true,
                'format' => 'yyyy-mm-dd',
                'todayHighlight' => true
        ]
    ])
                
            ],
            'hora',
             [
                 'attribute' => 'IDcitas_cliente',
                 'value' => 'iDcitasCliente.nombre',
             ],
            [
                 'attribute' => 'IDcitas_servicio',
                 'value' => 'iDcitasServicio.nombre',
            ],
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action,  $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'IDcitas' => $model->IDcitas]);
                 }
            ],
        ],
    ]); ?>
    </div> 
   </div> 
<br>
<!--Footer-->
<div class="footer">
  ManageBarbershop 2022
  </div>
</body>

views/citas/total.php
<?php

/** @var yii\web\View $this */

use circulon\widgets\ColumnListView;
use yii\helpers\Html;
use yii\bootstrap4\Modal;
use yii\helpers\Url;

$this->title = 'ManagerBarberShop';
?>
<body>
<?php
class CabeceraPagina {
  private $titulo;
  private $ubicacion;
  private $colorFuente;
  private $colorFondo;
  public function __construct($titulo,$ubica,$colorFuen,$colorFond)
  {
    $this->titulo=$titulo;
    $this->ubicacion=$ubica;
    $this->colorFuente=$colorFuen;
    $this->colorFondo=$colorFond;
  }
  public function mostrarHeader()
  {
    echo '<div style="font-size:30px;text-align:'.$this->ubicacion.';color:';
    echo $this->colorFuente.';background-color:'.$this->colorFondo.'">';
    echo $this->titulo;
    echo '</div>';

  }
}

$cabecera=new CabeceraPagina('HISTORIAL DE CITAS MENSUALES','center','#ffffff','#11264D');
$cabecera->mostrarHeader();

?>



<div class ="row justify-content-center  p-2  ">          
    <div class = "card col-2 m-2  zoom colorManager"> 
        <div class = "card-body">
        
             <div class = "card-body card sinborde negro">
          <?php echo Html::img('@web/image/home.png');?>
             </div>
            <hr class="colorBarber">
              <?= Html::a('HOME',['site/index'],['class' => 'card-body card colorManager2'])?>
        </div>
     </div>
    
    <div class = "card col-2 m-2  zoom colorManager "> 
        <div class = "card-body">
        
             <div class = "card-body card sinborde negro">
          <?php echo Html::img('@web/image/us.png');?>
             </div>
            <hr class="colorBarber">
              <?= Html::a('CLIENTES',['clientes/index'],['class' => 'card-body card colorManager2'])?>
        </div>
     </div>
    
    <div class = "card col-2 m-2  zoom colorManager"> 
        <div class = "card-body">
        
             <div class = "card-body card sinborde negro">
          <?php echo Html::img('@web/image/ser.png');?>
             </div>
            <hr class="colorBarber">
              <?= Html::a('SERVICIOS',['servicios/index'],['class' => 'card-body card colorManager2'])?>
        </div>
     </div>
    
    <div class = "card col-2 m-2  zoom colorManager"> 
        <div class = "card-body">
        
             <div class = "card-body card sinborde negro">
          <?php echo Html::img('@web/image/pro.png');?>
             </div>     
            <hr class="colorBarber">
              <?= Html::a('PROVEEDORES',['proveedores/index'],['class' => 'card-body card colorManager2'])?>
        </div>
     </div>
    
    <div class = "card col-2 m-2  zoom colorManager"> 
        <div class = "card-body">
        
             <div class = "card-body card sinborde negro">
          <?php echo Html::img('@web/image/sto.png');?>
             </div>
            <hr class="colorBarber">
            
              <?= Html::a('PRODUCTOS',['productos/index'],['class' => 'card-body card colorManager2'])?>
        </div>
    </div>
    
</div>
<br>

    
    <div class="row justify-content-center">
        <h4 class="card card-body m-2 colorBarber centrar sinborde"> A continuación se mostrará un calendario con los meses del año seleccione dando clic a cualquiera de los meses </h4> 
    </div>
    
    <div class ="row justify-content-center">
        <h2 class="card-body card col-3 m-2 colorManager "> 2022 </h2> 
    </div>
        
<br>
<br>
<div class="container ">
    <div class ="row justify-content-center ">

     
        <?= Html::a('Enero',['citas/enero'],['class' => 'card-body card col-3 m-2 colorManager zoom'])?>
        <?= Html::a('Febrero',['citas/febrero'],['class' => 'card-body card col-3 m-2 colorManager zoom'])?>
        <?= Html::a('Marzo',['citas/marzo'],['class' => 'card-body card col-3 m-2 colorManager zoom'])?>
        <?= Html::a('Abril',['citas/abril'],['class' => 'card-body card col-3 m-2 colorManager zoom'])?>
        <?= Html::a('Mayo',['citas/mayo'],['class' => 'card-body card col-3 m-2 colorManager zoom'])?>
        <?= Html::a('Junio',['citas/junio'],['class' => 'card-body card col-3 m-2 colorManager zoom'])?>
        <?= Html::a('Julio',['citas/julio'],['class' => 'card-body card col-3 m-2 colorManager zoom'])?>
        <?= Html::a('Agosto',['citas/agosto'],['class' => 'card-body card col-3 m-2 colorManager zoom'])?>
        <?= Html::a('Septiembre',['citas/septiembre'],['class' => 'card-body card col-3 m-2 colorManager zoom'])?>
        <?= Html::a('Octubre',['citas/octubre'],['class' => 'card-body card col-3 m-2 colorManager zoom'])?>
        <?= Html::a('Noviembre',['citas/noviembre'],['class' => 'card-body card col-3 m-2 colorManager zoom'])?>
        <?= Html::a('Diciembre',['citas/diciembre'],['class' => 'card-body card col-3 m-2 colorManager zoom'])?>
    
    </div> 
</div>

<br>
<!--Footer-->
<div class="footer">
  ManageBarbershop 2022
  </div>
</body>